### ISSUE TITLE
memory usage for ensemble too big

### ISSUE THREAD

**Issue by juanpablosimarro** [pySTEPS/pysteps#158]
Hello,

I'm trying to do the example plot_steps_nowcast.py from pySTEPS using OPERA.
The memory usage is big, more than 20 Gb. 
Is is normal?

Thank you

Juan

**Comment by pulkkins** [comment]
Considering the large size of the OPERA mosaics, this sounds normal if you are using 20 ensemble members. To reduce the memory usage, you can try passing domain="spectral" to steps.forecast.

**Comment by juanpablosimarro** [comment]
Thank you, that helps.

**Comment by dnerini** [comment]
> 
> 
> Thank you, that helps.

Good to hear! Do not hesitate to share your findings with us, does using the spectral domain reduce considerably the memory footprint of steps.forecast? By how much?

I just wanted to add that typically steps is run on relatively limited domains (order of 500 x 500 km). This has to do with the computational cost, but also because STEPS assumes stationarity of the rainfall statistics (mean, variance, and correlation structure) over the domain.

I'm closing this issue, but do not hesitate to reopen it if you need more support.
