### ISSUE TITLE
Specify dependency package versions in environment.yml

### ISSUE THREAD

**Issue by pkars** [pySTEPS/pysteps#16]
Currently the conda environment file (environment.yml) does not specify which versions of dependencies should be installed. It would be a good idea to specify package versions at least for required dependencies to prevent issues arising from different versions used.

I suggest we use current (latest) stable versions as our required versions, unless there's a reason to use an older version. As of writing this (Sept. 2018), the following versions are available from conda:

  - git 2.18.0
  - dask 0.19.1
  - numpy 1.15.1 
  - matplotlib 2.2.3
  - opencv 3.4.2
  - pillow 5.2.0
  - pyproj 1.9.5.1
  - scipy 1.1.0

**Comment by dnerini** [comment]
We need to revise the environment.yml before the next release.

For example, now jsmin and attrdict are listed, but these two packages are not available in the anaconda distribution and nees to be installed with pip. Hence, the current version of the environment.yml cannot be used with `conda env create -f environment.yml`.

**Comment by aperezhortal** [comment]
I was testing pysteps in a minimal environment, with out the optional dependencies listed below:

* opencv-python_ (for the Lucas-Kanade optical flow)
* pillow_ (for importing gif data)
* pyproj_ (for cartographic transformations and needed to import data)

The package functionality is quite minimal without these dependencies and the examples scripts provided can not run with out them.

Since many of them are already in the environment.yml, wouldn't be better to consider them as dependencies instead as optional packages? By doing so, the full functionality is available after the installation. 

This is not the case with **dask, toolz and pyfftw **,  they are indeed optional, since they help to improve the computational efficiency.

**Comment by dnerini** [comment]
OK, good idea, I've now listed opencv, pillow and pyproj as main dependencies (commit f157da9e223ba41f154ec238086476e0bd739e7d).

**Comment by aperezhortal** [comment]
Going back to the @pkars suggestion about the version numbers. The **environment.yml** file is used to create a the pysteps environment. When doing so, the anaconda installer will resolve the dependencies of the different packages listed in the **environment.yml** file and it will it install the latest versions available in anaconda channels that are configured.

**Comment by dnerini** [comment]
@aperezhortal 's comment seems to close this issue.
