### ISSUE TITLE
pysteps 0.2

### ISSUE THREAD

**Issue by dnerini** [pySTEPS/pysteps#17]
Since our first release in August, there have been a number of improvements and bug fixes that would justify a new release, in my opinion.

**Comment by pulkkins** [comment]
I agree on that. We need to prepare a changelog for the release. @dnerini, could you prepare a list of your changes since release 0.1 (just the most important ones). I will then merge that list with my own.

**Comment by dnerini** [comment]
OK, after the last pull request cf3273b440606b98da9aeb05a985386d3cb7dcfb from @aperezhortal, we are very close to issue pysteps 0.2. We are basically only missing the new pyVET module for optical flow. After that, I think we should have our new release.

This is my basic changelog since 0.1:
- Bug fixes.
- Performance and syntax improvements.
- New utility methods to adjust the domain by geographical coordinates.
- New data transformation methods: normal quantile, square-root and logarithmic transformations.
- New importer for MeteoSwiss' metranet data format.
- New shift and scale post-processing method.

**Comment by aperezhortal** [comment]
I added the VET module in the commit 257e80f4ee1d3455c65fd6e410ccadfd6939a6ed. I tried it with the the example data and gives results similar to the LK in the nowcasting and in the motion fields.

I also made a several changes in the motion interface to remove the nested ifs and use a dict instead (little faster and cleaner). I did a unitary testing for many possible combinations to ensure that this change does not introduced any bug.

See the min diff in https://github.com/pySTEPS/pysteps/commit/257e80f4ee1d3455c65fd6e410ccadfd6939a6ed#diff-e39de838352d1f6e85823ac4aa1ea32e. 

My change log for since version 0.1 is:
* Replace the config module with a JSON pystepsrc configuration file.
* Add the Variational Echo Tracking method to the motion module.

**Comment by dnerini** [comment]
@pulkkins can you provide your changelog since 0.1? Once I have it, I will issue version 0.2.

**Comment by pulkkins** [comment]
Here is my tentative changelog for version 0.2:

- More sensible naming of several main modules: optflow -> motion, advection -> extrapolation and postproc -> postprocessing.
- Add missing documentation to several modules and methods.
- New intensity-scale verification method.
- New visualization methods: cartopy backend, exceedance probabilities and plotting motion fields on a map.
- New interface module for different FFT methods and allow the user to choose the method.
- Fix incorrect separation into components when using the bps method for adding perturbations to the advection field.
- More efficient computation of the FFT in the cascade decomposition by using rfft2/irfft2 instead of fft2/ifft2.
- Two different methods for adjusting the temporal autocorrelation coefficients in order to guarantee stationarity of the resulting AR(2) models.
- Modify the STEPS method to have the same number of positional arguments as the other methods in the nowcasts module.
- Move the deterministic S-PROG mask computation outside the stochastic part of the STEPS method to avoid repeated computations.

**Comment by dnerini** [comment]
We are almost ready for pysteps 0.2. 
@pulkkins is updating the documentation and we still need to fix some minor bugs (see e.g. #29 ). Anything else that needs to be addressed before the release?

**Comment by dnerini** [comment]
I've drafted the new pysteps 0.2 release. Please, @pulkkins , @loforest and @aperezhortal have a look to it (you'll find it with the release link) before we publish it.

**Comment by loforest** [comment]
I extended a couple of sentences in the draft. It looks good!

**Comment by pulkkins** [comment]
Looks good! I did some small modifications.

I think we are ready to release pysteps 0.2. Though, I did some more
extensive modifications in the nowcasts.steps module (particularly commit
1784672). It needs to be checked that I didn't introduce any new bugs.

**Comment by dnerini** [comment]
OK, then I will check once more than everything works and then publish the release we have drafted.

**Comment by dnerini** [comment]
I tested the current version with the pysteps/examples scripts and everything looks fine. I will publish the 0.2 release tomorrow, unless somebody has something against it.

**Comment by dnerini** [comment]
https://github.com/pySTEPS/pysteps/releases/tag/v0.2 closes this issue. Many thanks to everyone for your contribution!
