### ISSUE TITLE
Odd Flow Direction during STEPS nowcast

### ISSUE THREAD

**Issue by 5fcgdaeb** [pySTEPS/pysteps#183]
I am trying to nowcast using the `STEPS` forecast method with the following details:

```
nwc_method = "steps"
oflow_method = "lucaskanade"
adv_method = "semilagrangian"
noise_method = "parametric"
bandpass_filter = "gaussian"
decomp_method = "fft"
```

It usually yields pretty good results but it has predicted an odd forecast for a case of mine. I am attaching the observations (input) and the forecasts (output) as video but I can surely provide the raw files as well.

### Observations
![observed](https://user-images.githubusercontent.com/877496/99376400-f21c0600-28d5-11eb-812a-c279e09e06f1.gif)

### Forecasts (Nowcasts)
![forecasted](https://user-images.githubusercontent.com/877496/99376393-ee887f00-28d5-11eb-8282-63246f4c64f3.gif)

I wasn't able to figure out why the nowcasts are pointing to a south-based flow when the observations have a clear north-east based flow. I am not really an expert on the domain so please feel free to close the issue if this is an user-error.

Thanks!

**Comment by pulkkins** [comment]
I believe this is because of limitations in the Lucas-Kanade method (and optical flow in general). There is growth of new precipitation especially in the lower part of your domain. In such cases the advection velocities cannot be reliably determined. Have you tested with other optical flow methods?

**Comment by 5fcgdaeb** [comment]
Oh, I see! I figured the new precipitation fields would be the source of the issue. In that case, I can try zooming in a bit more to make sure that I run the nowcast on a smaller, more focused area.

@pulkkins Which optical flow method would you recommend for this case?

**Comment by pulkkins** [comment]
You can try the Proesmans method. It gives a quality measure for the advection velocities based on forward-backward consistency. Based on the consistency, you can replace unreliable advection velocities by interpolation from those that are known to be reliable.

**Comment by dnerini** [comment]
Hello @5fcgdaeb 

On top of what @pulkkins already suggested, I'd like to say that LK is quite sensitive to the motion of the precipitation mask itself, that is, the limit between precipitation and non-precipitation. This is because the dry/wet transition is very sharp, meaning that the gradient is high, which is the criterion used by the Shi-Tomasi feature detection algorithm to define a good feature to track.

In your case, this might explain the resulting motion field. The overall motion of precipitation is north-west, but the precipitation *mask* somewhat appears to move south (also because of the growth of new precipitation areas).

With LK, you can try to account for that in some ways (but such cases remain quite challenging for all motion fields): 

1. Try to minimize the dry/wet discontinuity of your transformed field.
     - If transforming to reflectivity, make sure that the value assigned to dry pixels (`zerovalue`) is as close as possible to the value of your lowest wet pixels (`threshold`).
     - Try a different transformation, such as `sqrt_transform`.
     - Set all dry pixels to nan and pass a positive `buffer_mask` argument with the `fd_kwargs` argument. This will prevent the feature detection algorithm to use the dry/wet discontinuity as tracking feature.
2. Reduce the noise in the input data.
   - Some degree of prefiltering might help. 
   - Tune the preprocessing parameters in LK: `size_opening` and `nr_std_outlier` are some of the parameters that might help to reduce the noise.
   - In some cases (particularly with slow motions), it could help to estimate the motion on larger time intervals (say between fields 10 or 15 minute apart instead 5 minutes). This help to increase the motion signal. Just remember to rescale the estimated motion field accordingly before using it to make a forecast.
3. Improve the feature detection algorithm
    - The default parameters might not be appropriate for your data
    - Try the blob detection which instead should focus on the actual maxima in your field (or implement a new one that is better suited to your case).

Remember that you can always check the result of the sparse tracking algorithm before interpolation, see this example:
https://pysteps.readthedocs.io/en/latest/auto_examples/LK_buffer_mask.html#sphx-glr-auto-examples-lk-buffer-mask-py
This should help identify the cause of the problem.

Finally, you can compare the estimation from LK with more advanced optical flow methods such as Proesmans, as @pulkkins already suggested, but also VET would probably be a good reference.

Hope this helps!

**Comment by 5fcgdaeb** [comment]
This is excellent @dnerini, thanks! It gives so much insight into how the nowcasts are generated. I will now take a closer look at the examples gallery with this in mind.

I think we can close this issue, I do know where to look and what to do in case I see such odd flows/results.

Thanks everyone, really appreciated.
