### ISSUE TITLE
Pysteps is not available for Python 3.9 in conda-forge

### ISSUE THREAD

**Issue by pkars** [pySTEPS/pysteps#193]
Trying to install pysteps (1.4.0) in conda environment with Python 3.9 fails. This is because there is no pysteps package marked for that Python version. Running `conda search pysteps=1.4.0` shows that there are packages only for Python 3.6, 3.7 and 3.8.

As a workaround, installing pysteps with pip works under Python 3.9.

**Comment by aperezhortal** [comment]
Hi @pkars, that is correct. We are having issues building the conda package for python 3.9 in windows and osx. 
There is a [PR open in the pysteps-feedstock](https://github.com/conda-forge/pysteps-feedstock/pull/11) to include the latest python version. But some tests are failing because conda can't resolve the dependencies for pysteps. This seems to be an issue with the conda packages available for python 3.9 rather than a pysteps issue. 

Once this issue is fixed, we'll add a build for python 3.9.

**Comment by pkars** [comment]
Hi @aperezhortal, thanks for the response and the link to the pysteps-feedstock PR. Hopefully the conda issue gets resolved soon!

**Comment by dnerini** [comment]
Both v1.4.1 and v1.5 should now be available for python 3.9 (Linux and OSX only).
Feel free to reopen this issue if something's still wrong.
