### ISSUE TITLE
Implement importer for NWP (netcdf) data

### ISSUE THREAD

**Issue by ladc** [pySTEPS/pysteps#215]
Implement function to read in CF-compliant NetCDF data, not (yet) including interpolation to the radar / nowcasting grid. This might be simplified by moving to xarray first. Required for #212 .

**Comment by cvelascof** [comment]
@ladc working on that. I have just added one example with radar data and NWP rainfall forecasts into https://github.com/pySTEPS/pysteps-data

**Comment by RubenImhoff** [comment]
I just saw that the nwp importers do not give the coordinates of the middle of the cell, but of the left cell edge instead. The "_to_xarray" function in the decorators is skipped with the nwp data, because it is read as an xarray DataArray and therefore skipped by:
`if not isinstance(data_array, xr.DataArray):`

Should we directly set everything to the cell centers in the nwp importers, or should we adjust the decorators in such a way that it also knows how to work with this data?
