### ISSUE TITLE
pysteps documentation

### ISSUE THREAD

**Issue by dnerini** [pySTEPS/pysteps#57]
There are a couple of matters concerning documentation that I would like to discuss here before the V1.0.0 release.

First, currently the documentation is hosted on github pages: [https://pysteps.github.io/pysteps/refmanual/](https://pysteps.github.io/pysteps/refmanual/).
This means that the documentation needs to be manually updated. 
One alternative to this approach would be to use [readthedocs](https://readthedocs.org/), allowing the automatic update of the documentation after every new push to github. It also allows versioning, meaning that we'll be able to support the documentation for different releases.

Secondly, currently all methods need to be listed in the source file of the documentation (as in [here](https://raw.githubusercontent.com/pySTEPS/pysteps/master/doc/source/io.rst)). A different approach would be to to directly list them in the __init__.py file of each module as done in py-art, for example [here](https://github.com/ARM-DOE/pyart/blob/master/pyart/io/__init__.py). I would argue that this way may be easier to maintain, since the list for the documentation autosummary is kind in the same place of the code itself.

Any thoughts on these two points?

**Comment by aperezhortal** [comment]
Using readthedocs is the best alternative in my opinion. Besides the automatic updates, every time that we create a new tag, the documentation is also created for that tag (version). This maintains also the documentation of previous versions.

The py-art approach seems interesting. I will take a closer look at it.

**Comment by wcwoo** [comment]
I think readthedocs is pretty good for a public project.  By automating documentation generation it also ensures consistency between manuals and codes.

Since you are already using sphinx autodocs, perhaps you may consider letting it automatically pull all docstrings to generate manuals, such that there is no need to manually update anything.

**Comment by aperezhortal** [comment]
I pushed a branch with a documenation draft using the autosummary sphinx extension as in py-art. https://github.com/pySTEPS/pysteps/tree/new_documentation

I didn't include the documentation in the __init__.py files since it was not needed. Instead, I added the autosummary directory to several modules and add the documentation sources accordingly. 
Not all the modules were documented, since this is just a proposal.

This documentaiton is easier to maintain. Every time that we add a module with its own documentation, only a few lines need to be added to the *.rst sources. 

Here is the resulting documentation: http://www.meteo.mcgill.ca/~aperez/pysteps_doc_test/source/index.html

In the landing page, three main links can be followed:
- User reference: Here with can put an introductory guide, like a pysteps tutorial. For now, it is empty. 
- Developer reference: This is the API documentation. Every module is described. 
- Bibliography: A list of all the references. I had to made a separate page for this to solve some problems with missing citations in the documentation ([due to a sphinxcontrib-bibtex limitation](https://sphinxcontrib-bibtex.readthedocs.io/en/latest/usage.html#unresolved-citations-across-documents.)). 

I also used the [sphinx theme for read the docs](https://github.com/rtfd/sphinx_rtd_theme), with minor changes in the style.

**Comment by dnerini** [comment]
@aperezhortal, this looks excellent! I really like as this way the manual work is reduced to a minimum and consequently the documentation will be easier to maintain. Thanks a lot for this contribution!

I think we should implement this solution and use readthedocs for hosting it.

**Comment by aperezhortal** [comment]
Great! I will add the rest of the modules to the documentation and then make a pull request. Once it is merged, we can configure the read the docs to build the documentation automatically.

**Comment by dnerini** [comment]
I'm happy to help with this, I'll be working with you on the same branch.

Edit: now all basic modules should be there.

**Comment by dnerini** [comment]
The documentation is now online on readtheocs:
https://pysteps.readthedocs.io/en/latest/source

but there are still a number of issues:

1.  I had to comment out the `python>=3.6` requirement from the doc/requirements.txt file (5b8b728727f713174f5e40919446020b965cb7f3) in order to get the documentation to build successfully. That line caused the following error:

> /home/docs/checkouts/readthedocs.org/user_builds/pysteps/envs/latest/bin/python -m pip install --exists-action=w --cache-dir /home/docs/checkouts/readthedocs.org/user_builds/pysteps/.cache/pip -r doc/requirements.txt
Collecting python>=3.6 (from -r doc/requirements.txt (line 2))
  Could not find a version that satisfies the requirement python>=3.6 (from -r doc/requirements.txt (line 2)) (from versions: )
No matching distribution found for python>=3.6 (from -r doc/requirements.txt (line 2))

2. The documentation is accessible only at https://pysteps.readthedocs.io/en/latest/source while the simpler https://pysteps.readthedocs.io/ doesn't work.

3. The documentation is mostly incomplete, as all the methods are currently missing from some reason. Same for the bibliography page (empty). 

Edit: problem number 3 seems to be related to an old friend of ours:

> WARNING: autodoc: failed to import module 'cascade.interface' from module 'pysteps'; the following exception was raised:
> No module named 'pysteps.motion._vet'

Edit2: Here is the [full log](https://readthedocs.org/api/v2/build/8778389.txt).

Meaning that this will need some more work...

**Comment by aperezhortal** [comment]
Unfortunately, issue 3 still persists after merging PR #61.
[EDIT] : fd0ba65643967a842a8559ba11c7579d8bf78d74 solved the issue.

**Comment by dnerini** [comment]
Thanks @aperezhortal for all the fixes, now the documentation behaves as expected. 

I leave for the moment this issue open, since we still have to update the links to the new documentation, but this is now mostly completed, well done!

**Comment by dnerini** [comment]
All relevant links to the documentation are now updated.
