### ISSUE TITLE
Could you explain a bit more for  extrapolation "XYW = xy_coords + D - V_inc / 2.0"

### ISSUE THREAD

**Issue by Fangyh09** [pySTEPS/pysteps#84]
I am a bit confused at this line, would you explain it a bit more? Thanks!
https://github.com/pySTEPS/pysteps/blob/b98bb8923318c59d41e7ef54bfb40bb77a038e71/pysteps/extrapolation/semilagrangian.py#L131

**Comment by pulkkins** [comment]
The method used here is a generalization of the midpoint rule for numerical integration (see https://math.libretexts.org/Bookshelves/Calculus/Map%3A_Calculus_-_Early_Transcendentals_(Stewart)/7%3A_Techniques_of_Integration/7.7%3A_Approximate_Integration). Here the integration variable is time (t) instead of x, and the function f is replaced with the advection field.

**Comment by Fangyh09** [comment]
@pulkkins I see, thanks.
