### ISSUE TITLE
Why AR(2) model is used on Lagrangian persistence component instead of original data?

### ISSUE THREAD

**Issue by Fangyh09** [pySTEPS/pysteps#89]
For line 204, why images are backward  extrapolated first before autoregression?

https://github.com/pySTEPS/pysteps/blob/df090c0a6e7df69596543d9bb739eb927a482395/pysteps/nowcasts/sprog.py#L190-L207

**Comment by dnerini** [comment]
Precisely because we seek at quantifying the _Lagrangian_ persistence, since this is the framework used for the advection forecast. In other words, we need to estimate the predictability of the extrapolation nowcast in order to simulate its forecast error.
You can find more details in, for example, [Seed (2003)](https://journals.ametsoc.org/doi/full/10.1175/1520-0450%282003%29042%3C0381%3AADASSA%3E2.0.CO%3B2).

Hope this helps.

**Comment by Fangyh09** [comment]
@dnerini Thanks, I have read the paper and know why to do so.
By the way, I am a bit confused by the combination of the auto-regression and advection(advecting each level with same displacement).
From my understanding, auto regression on lagrangian persistence component has achieved the effect of advection, why we need advection again? 

![image](https://user-images.githubusercontent.com/9389269/58960093-00a55900-87d9-11e9-846f-316de8ca9163.png)
in [Seed (2003)](https://journals.ametsoc.org/doi/pdf/10.1175/1520-0450%282003%29042%3C0381%3AADASSA%3E2.0.CO%3B2)

**Comment by Fangyh09** [comment]
I knew the reason. Without advection, some areas will always be no-rain days.
